# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe17eb8197aeb91cf6dbdcd889c43f611934f616e4c812817e5a604b98b1553eb575c769708df0315cdb5e4ae491204b3e3421add0cda0a56f7dd87bba3632a0

test:
  secret_key_base: a8a2f2560c62d6cbb7ad9d7ab5b54d954487930bd8d714d6af4d0c7024c65d9b1730383970f3ed355f7f2cd119971431c97c07622f1fc87185f70d0919f25eb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
